### ISSUE TITLE
How to calculate feature similarity？

### ISSUE THREAD

**Issue by XiaoyeAsZ** [prathebaselva/FORA#1]
Hi, I am trying to verify the similarity among iterations and get conflict result with the paper. 
Here, I work with Dit model and DPMSolverMultistepScheduler from diffusers library :

pipe = DiTPipeline.from_pretrained(
    "facebook/DiT-XL-2-256",
    torch_dtype=torch.float16,
    cache_dir="/data/huggingface/hub",
)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)

pipe = pipe.to("cuda")
words = ["white shark"]
class_ids = pipe.get_label_ids(words)
generator = torch.manual_seed(3)

when I modify diffusers library to print difference (with abs()) of feature in adjacent twice sample, I get the result as shown in picture
![Screenshot 2024-07-10 at 18 36 02](https://github.com/prathebaselva/FORA/assets/87251852/55f44311-1fc7-4558-9770-25505a583515)

It seems similarity of adjacent feature is not high enough to get 100%, which is reported by the paper. So could anyone give me some tips on how the paper calculate feature similarity. Your help will be highly appreciated.

**Comment by prathebaselva** [comment]
Hi,
Can you elaborate more on this. I do not understand perfectly which similarity matrix are you computing. The similarity matrix in FORA is computed using cosine similarity of attn and MLP between timesteps for same layers.
"It seems similarity of adjacent feature is not high enough to get 100%, " , we cannot achieve 100%. Can you point out where this has been claimed?

**Comment by XiaoyeAsZ** [comment]
> Hi,
> Can you elaborate more on this. I do not understand perfectly which similarity matrix are you computing. The similarity matrix in FORA is computed using cosine similarity between timesteps for same layers.
> "It seems similarity of adjacent feature is not high enough to get 100%, " , we cannot achieve 100%. Can you point out where this has been claimed?

Thanks for reaching out. 
Exactly, I calculate similarity directly using euclidean distance because I find the paper replace the whole feature with the previous one, and I try to find out how much error this will introduce. Sorry for 100% similarity, actually I mean almost 100%, as heatmap (Fig.2) shown.
Btw, it seems that the method in the paper is equal to step several times with the same noise, so why we can't modify the scheduler directly rather than inferencing of the model ?

**Comment by Ting-Justin-Jiang** [comment]
I think the original paper calculates cosine similarities with DDPM (250 steps instead of DPMSolver++ 20 steps).

**Comment by prathebaselva** [comment]
- Euclidean will give good results as well ( With some ablation study done on our end). So the metric is your choice. We found L2 to be better than L1. 
- "the method in the paper is equal to step several times with the same noise" - This is not true. We are only caching the Attention and MLP layers. time component is used for scale and shift.
- "why we can't modify the scheduler directly rather than inferencing of the model " - I do not understand your point. Can you please elaborate?

**Comment by XiaoyeAsZ** [comment]
> * Euclidean will give good results as well ( With some ablation study done on our end). So the metric is your choice. We found L2 to be better than L1.
> * "the method in the paper is equal to step several times with the same noise" - This is not true. We are only caching the Attention and MLP layers. time component is used for scale and shift.
> * "why we can't modify the scheduler directly rather than inferencing of the model " - I do not understand your point. Can you please elaborate?

Sorry for late reply. 
* From "time component is used for scale and shift" , I got why I  come to the wrong conclusion "the method in the paper is equal to step several times with the same noise".
* Meanwhile, I don't think conflict I observed on similarity derive from different sampling steps between DDPM & DPMSolver. Because I do observe it in first several layers in Dit (approximate layer 0 - layer 13). But when it come to layer 27 (last layer in Dit) , similarity between adjacent steps severely disappear.

**Comment by prathebaselva** [comment]
"But when it come to layer 27 (last layer in Dit) , similarity between adjacent steps severely disappear." - Your observation is correct. There is high dissimilarity even between layer 0 and layer 1. There are ways to address this and we are working on getting the next version out which takes into consideration all this. 
But the main focus point of FORA is "simplicity Vs performance" . The observation we had with preliminary experimentation is that these minor tweaks for layers and even more along this line though might improve the FiD score lightly , we lose the simplest way to get faster sampling for minor loss in FiD.
